version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: root

  terraform:
    image: "hashicorp/terraform:1.1.7"
    entrypoint: [ "/bin/sh", "/opt/terraform/recipe.sh", "docker" ]
    working_dir: /opt/terraform
    depends_on:
      - dynamodb-local
    volumes:
      - "./terraform:/opt/terraform"
